apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  namespace: test-kustomize
spec:
  template:
    spec:
      containers:
        - name: example-app
          image: <+serviceConfig.serviceDefinition.spec.variables.image>
